server:
  port: 10001
spring:
  profiles:
    active: huawei
  application:
    name: SERVICE-UAA
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.linaxhua.file_transfer.common.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  instance:
    instance-id: uaa-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://rm-uf6ck33a76x59qa8q.mysql.rds.aliyuncs.com:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: filetransfer
    password: filetransfer
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.49:6001/eureka
---
spring:
  profiles: ali
  datasource:
    url: jdbc:mysql://rm-uf6ck33a76x59qa8q9o.mysql.rds.aliyuncs.com:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: filetransfer
    password: filetransfer
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.19.105.16:6001/eureka/
---
spring:
  profiles: huawei
  datasource:
    url: jdbc:mysql://rm-uf6ck33a76x59qa8q9o.mysql.rds.aliyuncs.com:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: filetransfer
    password: filetransfer
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.62:6001/eureka/