server:
  port: 7001
spring:
  profiles:
    active: dev
  application:
    name: GATEWAY-ZUUL
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
    instance-id: zuul-${server.port}
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator
zuul:
  prefix: /api # 路由前缀
  sensitive-headers: # Cookie,Set-Cookie,Authorization
  routes:
    SERVICE-UAA:
      path: /uaa/**
    SERVICE-SERVER:
      path: /server/**


# 下面的设置针对超大文件上传（比如500M），提升了超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 3000

ribbon:
  ConnectionTimeout: 2000
  ReadTimeout: 30000
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.49:6001/eureka/
