server:
  port: 8001
spring:
  profiles:
    active: test
  application:
    name: SERVICE-SERVER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  instance:
    instance-id: provider-${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
ribbon:
  eureka:
    enabled: true
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.linaxhua.file_transfer.common.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
socket-port:
  socket-thread-size: 4
  file-handle-thread-size: 4
  start-port: 40000
  end-port: 40100
  file-max-size: 104857600  #分片大小
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://rm-uf6ck33a76x59qa8q9o.mysql.rds.aliyuncs.com:3306/file_transfer?useUnicode=true&characterEncoding=utf8
    username: filetransfer
    password: filetransfer
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.49:6001/eureka