server:
  port: 6001
eureka:
  server:
    eviction-interval-timer-in-ms: 30000
  instance:
    instance-id: eureka-${server.port}
    hostname: eureka-${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/